
# nacos:
#   config:
#     server-addr: ${NACOS_SERVER_ADDRESS}
#   discovery:
#     server-addr: ${NACOS_SERVER_ADDRESS}
#   client:
#     ip: ${NACOS_CLIENT_ADDRESS}
spring:
  http:
    proxy:
      host: 127.0.0.1
      port: 7890
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-auth
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: ${NACOS_SERVER_ADDRESS}
  security:
    jwt:
      key: ${JWT_KEY:123456}
      expire: ${JWT_EXPIRE:24}
      limit:
        basic: ${JWT_FRESH_LIMIT_BASIC:60}
        aggresive: ${JWT_FRESH_LIMIT_AGGRESIVE:15}
        alter_frequency: ${JWT_FRESH_LIMIT_ALTER_FREQ:4}
  # datasource:  # 配置mysql
  #   url: ${DATASOURCE_ADDRESS}
  #   username: ${DATASOURCE_USERNAME}
  #   password: ${DATASOURCE_PASSWORD}
  # data:
  #   redis:
  #     host: ${REDIS_HOST}
  #     port: ${REDIS_PORT}
  #     password: ${REDIS_PASSWORD}
  mail:
    host: ${MAIL_HOST:1}
    username: ${MAIL_USERNAME:1}
    password: ${MAIL_PASSWORD:1}
    login-url: ${MAIL_LOGIN_URL:/api/auth/login/email}
    verify-cd: ${MAIL_VERIFY_CD:60}
    verify-available: ${MAIL_VERIFY_AVAILABLE:10}
server:
  port: ${SERVER_PORT:8080}  # 默认端口
  servlet:
    encoding:
      charset: UTF-8 # 默认值
      force-response: true
springdoc:
  api-docs:
    path: "/docs/api"
  # swagger-ui:
  #   path: "/docs/swagger"
  #   operationsSorter: method
logging:
  file:
    name: logs/demoApp.file.log
snowflake:
  datacenterId: ${DATACENTER:0}
  user:
    workId: ${USERCENTERID:0}
  group:
    workId: ${GROUPCENTERID:1}
frontend:
  address: ${FRONT_ADDRESS:localhost:8081}

